if(ZMQ)
    # Find libzmq
    if(NOT MSVC)
        pkg_check_modules(PKG_LIBZMQ libzmq)
        find_path(LIBZMQ_INCLUDE_DIR zmq.h HINTS ${PKG_LIBZMQ_INCLUDE_DIRS})
        find_library(LIBZMQ_LIBRARY zmq HINTS ${PKG_LIBZMQ_LIBRARY_DIRS})

        if(LIBZMQ_INCLUDE_DIR AND LIBZMQ_LIBRARY)
            message(STATUS "ZMQ: found - ${LIBZMQ_INCLUDE_DIR}, ${LIBZMQ_LIBRARY}")
            add_definitions(-DHASZMQ)
            set(ZMQ_INCLUDE_DIRS ${LIBZMQ_INCLUDE_DIR})
            set(ZMQ_LIBRARIES ${LIBZMQ_LIBRARY})
        else()
            message(STATUS "ZMQ: not found.")
        endif()

    elseif(MSVC_VCPKG)

        find_package(ZeroMQ)

        if(ZeroMQ_FOUND)
            add_definitions(-DHASZMQ)
            set(ZMQ_LIBRARIES libzmq)
            Message(STATUS "ZMQ: found (VCPKG) - " ${ZMQ_LIBRARIES})
        else()
            Message(STATUS "ZMQ: not found (VCPKG).")
        endif()

    else()
        find_path(ZMQ_INCLUDE_DIR zmq.h HINTS ${POTHOSSDR_INCLUDE_DIR})

        file(GLOB ZMQ_LIBRARY_CANDIDATES "${POTHOSSDR_LIBRARY_DIR}/libzmq*.lib")
        if(ZMQ_LIBRARY_CANDIDATES)
            list(GET ZMQ_LIBRARY_CANDIDATES 0 ZMQ_LIBRARY)
        endif()

        file(GLOB ZMQ_DLL_CANDIDATES "${POTHOSSDR_BINARY_DIR}/libzmq*.dll")
        if(ZMQ_DLL_CANDIDATES)
            list(GET ZMQ_DLL_CANDIDATES 0 ZMQ_DLL)
        endif()

        if(ZMQ_INCLUDE_DIR AND ZMQ_LIBRARY AND ZMQ_DLL)
            Message(STATUS "ZMQ: found (PothosSDR) - " ${ZMQ_INCLUDE_DIR}, ${ZMQ_LIBRARY}, ${ZMQ_DLL})
            set(COPY_ZMQ_DLL TRUE)
            set(COPY_PTHREAD_LIBUSB_DLL TRUE)
            add_definitions(-DHASZMQ)
            set(ZMQ_INCLUDE_DIRS ${ZMQ_INCLUDE_DIR})
            set(ZMQ_LIBRARIES ${ZMQ_LIBRARY})
        else()
            Message(STATUS "ZMQ: NOT found (PothosSDR) - " ${ZMQ_INCLUDE_DIR}, ${ZMQ_LIBRARY}, ${ZMQ_DLL})
        endif()
    endif()
endif()
